class Error_DB(Exception):
    pass

class Error_Logico(Error_DB):
    pass